version: '3.5'

services:

    backend:
        image: anntey/melanoma-backend:latest
        #build: ./backend
        ports:
            - '8000:8000'

    frontend:
        image: anntey/melanoma-frontend:latest
        #build: ./frontend
        ports:
            - '3000:3000'
        depends_on:
            - backend